# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mylogin', '0003_users_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('FK_poke_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_user', to='mylogin.Users')),
                ('FK_poke_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poke_target', to='mylogin.Users')),
            ],
        ),
    ]
