# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0003_users_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='alias',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='name',
        ),
    ]
